apiVersion: v1
kind: ServiceAccount
metadata:
  name: basebook-backend
  namespace: basebook
  labels:
    app: basebook-dex
    component: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: basebook-router
  namespace: basebook
  labels:
    app: basebook-dex
    component: router
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: basebook-frontend
  namespace: basebook
  labels:
    app: basebook-dex
    component: frontend
